### ISSUE TITLE
Strange behavior when using multiplug badges

### ISSUE THREAD

**Issue by MellKam** [okikio/bundlejs#54]
Here is an example of the part of my readme where I tried to compare the sizes of packages

| Package | Base API | Minified size | Minified and gzipped size |
| --- | --- | --- | --- |
| yumi-fetch | fetch | <a href="https://bundlejs.com/?q=yumi-fetch&treeshake=%5B%7Byumi%7D%5D" alt="Minified size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=yumi-fetch&treeshake=[{yumi}]&badge=minified" /></a> | <a href="https://bundlejs.com/?q=yumi-fetch&treeshake=%5B%7Byumi%7D%5D" alt="Minified and gripped size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=yumi-fetch&treeshake=[{yumi}]&badge=" /></a> |
| <a href="https://github.com/elbywan/wretch">wretch</a> | fetch | <a href="https://bundlejs.com/?q=wretch&treeshake=%5B%7Bdefault+as+wretch%7D%5D" alt="Minified size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=wretch&treeshake=[{default+as+wretch}]&badge=minified" /></a> | <a href="https://bundlejs.com/?q=wretch&treeshake=%5B%7Bdefault+as+wretch%7D%5D" alt="Minified and gripped size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=wretch&treeshake=[{default+as+wretch}]&badge=" /></a> |
| <a href="https://github.com/sindresorhus/ky">ky</a> | fetch | <a href="https://bundlejs.com/?q=ky&treeshake=%5B%7Bdefault+as+ky%7D%5D" alt="Minified size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=ky&treeshake=[{default+as+ky}]&badge=minified" /></a> | <a href="https://bundlejs.com/?q=ky&treeshake=%5B%7Bdefault+as+ky%7D%5D" alt="Minified and gripped size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=ky&treeshake=[{default+as+ky}]&badge=" /></a> |
| <a href="https://github.com/axios/axios">axios</a> | XMLHttpRequest | <a href="https://bundlejs.com/?q=axios&treeshake=%5B%7Baxios%7D%5D" alt="Minified size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=axios&treeshake=[{axios}]&badge=minified" /></a> | <a href="https://bundlejs.com/?q=axios&treeshake=%5B%7Baxios%7D%5D" alt="Minified and gripped size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=axios&treeshake=[{axios}]&badge=" /></a> |
| <a href="https://github.com/sindresorhus/got">got</a> | XMLHttpRequest | <a href="https://bundlejs.com/?q=got&treeshake=%5B%7Bdefault+as+got%7D%5D" alt="Minified size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=got&treeshake=[{default+as+got}]&badge=minified" /></a> | <a href="https://bundlejs.com/?q=got&treeshake=%5B%7Bdefault+as+got%7D%5D" alt="Minified and gripped size badge from bundlejs.com"><img src="https://deno.bundlejs.com/?q=got&treeshake=[{default+as+got}]&badge=" /></a> |

![image](https://github.com/okikio/bundlejs/assets/51422045/17f3e862-a187-4f54-a2cb-e28801254461)

At first it was working fine, but now it sticks and shows the previous size. Maybe it is cache issue or something else. I've tried opening it from different devices and it work the same way

**Comment by okikio** [comment]
Yeah, that was a caching issue, it would've resolved itself in about a day, but I've manually cleared the cache so the issue should now be resolved, let me know what you think

**Comment by MellKam** [comment]
Now some of them are correct, but still some are jumbled up in a random order.
![image](https://github.com/okikio/bundlejs/assets/51422045/854c58c4-c506-4d13-ad33-11a9f7b30637)

I've had this problem for more than a day. At first I also thought it would go away on its own, but it wasn't. So I decided to write the issue.

**Comment by okikio** [comment]
I think for some reason it's strongly caching the badges, I'll have to look into that. Thus far I've cleared all the badges so it should now work please open the table above in an incognito window to confirm. I'll work on a permanent fix for it's strongly held cache

**Comment by MellKam** [comment]
Okay, thanks for response

Still doesn't work, even in the incognito window. Although, now they are in a different order 😆
![image](https://github.com/okikio/bundlejs/assets/51422045/312dcf48-5d39-4fcb-a8b2-7c445e1ddc10)

**Comment by okikio** [comment]
It is a caching issue but it's specific to badges not the JSON response and I can't replicate it anymore, but it definitely does occur, I'll look further into this tmrw

**Comment by okikio** [comment]
Wait, nvm I've now created a fix, give it a try

**Comment by MellKam** [comment]
Yes, it's working well now. And it looks like I had some kind of error with the axios treeshake export. Thanks!
